meta_product_name: "Tastogether"
meta_title: "Tastogether - What is taste without buds?"
meta_description: "Discover nearby food experiences with Tastogether. Join a tasting or host one. Be curious. Discover new flavours. Share. Repeat!"
meta_image: "meta_image.png"